# Generated by Django 4.2.30 on 2026-06-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_created_user_joined_user_last_updated'),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEntrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entromment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.entrollment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UnitEntrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('entromment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_entrollment', to='mypage.sectionentrollment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
