# Generated by Django 4.2.30 on 2026-05-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=245)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.course')),
            ],
        ),
    ]
