# Generated by Django 4.2.30 on 2026-06-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_last_updated'),
        ('mypage', '0002_sectionentrollment_unitentrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionentrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unitentrollment',
            name='user',
        ),
        migrations.AddField(
            model_name='sectionentrollment',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
        migrations.AddField(
            model_name='unitentrollment',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.unit'),
        ),
    ]
