# Generated by Django 4.2.30 on 2026-05-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=245)),
                ('quize', models.CharField(max_length=245)),
                ('video', models.CharField(max_length=245)),
                ('description', models.CharField(max_length=245)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.section')),
            ],
        ),
    ]
