# Generated by Django 4.2.30 on 2026-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
