# Generated by Django 4.2.30 on 2026-05-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='quize',
        ),
        migrations.AddField(
            model_name='unit',
            name='quiz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
