# Generated by Django 4.2.30 on 2026-06-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_last_updated'),
        ('users', '0003_rename_created_user_joined_user_last_updated'),
        ('mypage', '0004_alter_entrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitentrollment',
            name='entromment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_entrollment', to='mypage.sectionentrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='entrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionentrollment',
            unique_together={('section', 'entromment')},
        ),
        migrations.AlterUniqueTogether(
            name='unitentrollment',
            unique_together={('unit', 'entromment')},
        ),
    ]
