# Generated by Django 4.2.30 on 2026-05-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_remove_unit_quize_unit_quiz_alter_unit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
