# Generated by Django 4.2.30 on 2026-06-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_last_updated'),
        ('mypage', '0005_alter_unitentrollment_entromment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrollment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
