# Generated by Django 4.2.30 on 2026-07-01 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_alter_entrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrollment',
            name='entrollment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sectionentrollment',
            name='entromment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_entrollment', to='mypage.entrollment'),
        ),
    ]
