# Generated by Django 4.2.30 on 2026-05-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='quiz',
        ),
    ]
