# Generated by Django 4.2.30 on 2026-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_entrollment_entrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidYouKnowFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
