# Generated by Django 4.2.30 on 2026-05-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_remove_unit_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
