# Generated by Django 4.2.30 on 2026-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0010_entrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='quiz',
            field=models.CharField(blank=True, max_length=245, null=True),
        ),
    ]
