# Generated by Django 4.2.30 on 2026-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0011_unit_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.URLField()),
                ('capital', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
    ]
