# Generated by Django 4.2.30 on 2026-06-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0012_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
