# Generated by Django 4.2.30 on 2026-06-08 12:08

from django.db import migrations, models
import mypage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0013_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mypage.models.upload_image),
        ),
    ]
