# Generated by Django 4.2.30 on 2026-07-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.unit'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.section'),
        ),
    ]
